apiVersion: v1
kind: Secret
metadata:
  name: simple-webapp-color-secret
  labels:
    app: simple-webapp-color
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        secretKeyRef:
          name: simple-webapp-color-secret
          key: app-color
    ports:
    - containerPort: 8080
