apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-env-from-configmap
  labels:
    app: simple-webapp-color
spec:
  containers:
  - image: mmumshad/simple-webapp-color
  name: simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: color-config
          key: app-color
