apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-hostpath
spec:
  storageClassName: localstorage
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
